### PR TITLE
Feature/update documentation

### PR DESCRIPTION
**Pull request by AlexAxthelm**
Updates for documentation. If there's anything important I've missed, let me know as a comment?

### CODE REVIEW

**Review by evan-2deg — CHANGES_REQUESTED** [review]
I need more details around the main readme documentation updates.  All others look good.

**Comment by AlexAxthelm** [comment]
The original readme was moved to `/docs/design_philosophy.md` in commit [46d9148](https://github.com/2DegreesInvesting/2dii-DataWarehouse/commit/46d9148bc39cb1c2ef9f6c476ccdbc3ec65db786#diff-04c6e90faac2675aa89e2176d2eec7d8)

**Comment by evan-2deg** [comment]
Approved

**Review by evan-2deg — APPROVED** [review]
Comment added - approving.

**Pull request merged**
